# Generated by json_schema_to_code v1.0.1 : json_schema_to_code subtraction_complete_schema.jinja.json /python/explayn-dh-agent/explayn_dh_agent/barbara/db/app_object_definitions/maths/basic_operations/subtraction/activities/complete/subtraction_complete_dataclass_generated.py --language python # noqa: E501
from __future__ import annotations

from dataclasses import dataclass, field

from dataclasses_json import dataclass_json
from explayn_dh_agent.barbara.activities.base.activity_state import ActivityState
from explayn_dh_agent.barbara.db.app_object_definitions.maths.basic_operations.activities.complete.basic_operations_dataclass import (
    InputRowState,
    OperandRowState,
)

NoneOrInt = None | int


@dataclass_json
@dataclass(kw_only=True)
class SubtractionCompleteProblem:
    minuend: int = 0
    subtrahend: int = 0


@dataclass_json
@dataclass(kw_only=True)
class SubtractionCompleteState:
    borrowing_row: list[NoneOrInt] = field(default_factory=list)
    adjusted_minuend_row: list[NoneOrInt] = field(default_factory=list)
    result_row: list[NoneOrInt] = field(default_factory=list)


@dataclass_json
@dataclass(kw_only=True)
class SubtractionCompleteUIData:
    """
    Complete UI state for the subtraction activity view.
    Built by the agent/backend and consumed by the Unity view.
    """

    question_text: str = ""
    minuend_row: OperandRowState = field(default_factory=lambda: OperandRowState())
    subtrahend_row: OperandRowState = field(default_factory=lambda: OperandRowState())
    borrowing_row: InputRowState = field(default_factory=lambda: InputRowState())
    adjusted_minuend_row: InputRowState = field(default_factory=lambda: InputRowState())
    result_row: InputRowState = field(default_factory=lambda: InputRowState())


@dataclass_json
@dataclass(kw_only=True)
class SubtractionCompleteData(ActivityState):
    problem: SubtractionCompleteProblem
    state: SubtractionCompleteState = field(default_factory=lambda: SubtractionCompleteState())
    ui_data: SubtractionCompleteUIData = field(default_factory=lambda: SubtractionCompleteUIData())
