// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using EduObject.Maths.BasicOperations.Activities.Complete;

namespace EduObject.Maths.BasicOperations.Subtraction.Activities.Complete
{
    [Serializable]
    public class SubtractionCompleteUIData{
        [JsonProperty("question_text")]
        public string QuestionText { get; set; } = "";
        [JsonProperty("minuend_row")]
        public OperandRowState MinuendRow { get; set; } = null;
        [JsonProperty("subtrahend_row")]
        public OperandRowState SubtrahendRow { get; set; } = null;
        [JsonProperty("borrowing_row")]
        public InputRowState BorrowingRow { get; set; } = null;
        [JsonProperty("adjusted_minuend_row")]
        public InputRowState AdjustedMinuendRow { get; set; } = null;
        [JsonProperty("result_row")]
        public InputRowState ResultRow { get; set; } = null;
        public SubtractionCompleteUIData(string question_text, OperandRowState minuend_row, OperandRowState subtrahend_row, InputRowState borrowing_row, InputRowState adjusted_minuend_row, InputRowState result_row)    {
            this.QuestionText = question_text;
            this.MinuendRow = minuend_row;
            this.SubtrahendRow = subtrahend_row;
            this.BorrowingRow = borrowing_row;
            this.AdjustedMinuendRow = adjusted_minuend_row;
            this.ResultRow = result_row;
        }
        // Parameterless constructor for Unity editor and serialization
        public SubtractionCompleteUIData() { }
    }


}
