// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
[Serializable]
public class AdditionExercise{
    public conststring type = "exercise/maths/basic_operations/addition";
    public AdditionExerciseProblem problem;
    public AdditionExerciseState state;
    public string correct_answer;
    public string question_text;
    public AdditionExercise(string type, AdditionExerciseProblem problem, AdditionExerciseState state, string correct_answer, string question_text)    {
        this.type = type;
        this.problem = problem;
        this.state = state;
        this.correct_answer = correct_answer;
        this.question_text = question_text;
    }
}
[Serializable]
public class AdditionExerciseProblem{
    public List<int> operands;
    public AdditionExerciseProblem(List<int> operands)    {
        this.operands = operands;
    }
}
[Serializable]
public class AdditionExerciseState{
    public List<int> carry_over_row;
    public List<int> result_row;
    public AdditionExerciseState(List<int> carry_over_row, List<int> result_row)    {
        this.carry_over_row = carry_over_row;
        this.result_row = result_row;
    }
}
