// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using JsonSubTypes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
[Serializable]
public class Geometry{
    public List<GeometryObject> objects;
    public List<Constraint> constraints;
    public List<Style> styles;
    public Geometry(List<GeometryObject> objects, List<Constraint> constraints, List<Style> styles)    {
        this.objects = objects;
        this.constraints = constraints;
        this.styles = styles;
    }
}
[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectPoint), "point")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectSegment), "segment")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectLine), "line")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectRay), "ray")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectVector), "vector")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectTriangle), "triangle")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectQuadrilateral), "quadrilateral")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectCircle), "center")]
public class GeometryObject{
    public string type;
    public GeometryObject(string type)    {
        this.type = type;
    }
}
[Serializable]
public class GeometryObjectPoint : GeometryObject
{
    public new string type = "point";
    public string name;
    public List<float>? coordinate;
    public GeometryObjectPoint(string type, string name, List<float>? coordinate): base("point")
    {
        this.type = type;
        this.name = name;
        this.coordinate = coordinate;
    }
}
[Serializable]
public class GeometryObjectSegment : GeometryObject
{
    public new string type = "segment";
    public List<string> points;
    public GeometryObjectSegment(string type, List<string> points): base("segment")
    {
        this.type = type;
        this.points = points;
    }
}
[Serializable]
public class GeometryObjectLine : GeometryObject
{
    public new string type = "line";
    public List<string>? points;
    public GeometryObjectLine(string type, List<string>? points): base("line")
    {
        this.type = type;
        this.points = points;
    }
}
[Serializable]
public class GeometryObjectRay : GeometryObject
{
    public new string type = "ray";
    public List<string> points;
    public GeometryObjectRay(string type, List<string> points): base("ray")
    {
        this.type = type;
        this.points = points;
    }
}
[Serializable]
public class GeometryObjectVector : GeometryObject
{
    public new string type = "vector";
    public List<string> points;
    public GeometryObjectVector(string type, List<string> points): base("vector")
    {
        this.type = type;
        this.points = points;
    }
}
[Serializable]
public class GeometryObjectTriangle : GeometryObject
{
    public new string type = "triangle";
    public string kind;  // Allowed values: "isosceles", "equilateral", "general"
    public List<string> points;
    public GeometryObjectTriangle(string type, string kind, List<string> points): base("triangle")
    {
        this.type = type;
        this.kind = kind;
        this.points = points;
    }
}
[Serializable]
public class GeometryObjectQuadrilateral : GeometryObject
{
    public new string type = "quadrilateral";
    public string kind;  // Allowed values: "square", "rectangle", "rhombus", "parallelogram", "trapezoid", "kite", "general"
    public List<string>? points;
    public GeometryObjectQuadrilateral(string type, string kind, List<string>? points): base("quadrilateral")
    {
        this.type = type;
        this.kind = kind;
        this.points = points;
    }
}
[Serializable]
public class GeometryObjectCircle : GeometryObject
{
    public new string type = "center";
    public string center;
    public float radius;
    public GeometryObjectCircle(string type, string center, float radius): base("center")
    {
        this.type = type;
        this.center = center;
        this.radius = radius;
    }
}
[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(ConstraintDistanceFixed), "distance_fixed")]
[JsonSubtypes.KnownSubType(typeof(ConstraintDistanceEquals), "distance_equals")]
[JsonSubtypes.KnownSubType(typeof(ConstraintAngleFixed), "angle_fixed")]
[JsonSubtypes.KnownSubType(typeof(ConstraintAngleEquals), "angle_equals")]
public class Constraint{
    public string type;
    public Constraint(string type)    {
        this.type = type;
    }
}
[Serializable]
public class ConstraintDistanceFixed : Constraint
{
    public new string type = "distance_fixed";
    public float distance;
    public ConstraintDistanceFixed(string type, float distance): base("distance_fixed")
    {
        this.type = type;
        this.distance = distance;
    }
}
[Serializable]
public class ConstraintDistanceEquals : Constraint
{
    public new string type = "distance_equals";
    public ConstraintDistanceEquals(string type): base("distance_equals")
    {
        this.type = type;
    }
}
[Serializable]
public class ConstraintAngleFixed : Constraint
{
    public new string type = "angle_fixed";
    public float angle;
    public ConstraintAngleFixed(string type, float angle): base("angle_fixed")
    {
        this.type = type;
        this.angle = angle;
    }
}
[Serializable]
public class ConstraintAngleEquals : Constraint
{
    public new string type = "angle_equals";
    public ConstraintAngleEquals(string type): base("angle_equals")
    {
        this.type = type;
    }
}
[Serializable]
public class Style{
    public string name;
    public string color;
    public float strokeWidth;
    public Style(string name, string color, float strokeWidth)    {
        this.name = name;
        this.color = color;
        this.strokeWidth = strokeWidth;
    }
}
