[project]
name = "json_schema_to_code"
version = "1.0.0"
description = "Generate code from JSON Schema definitions"
requires-python = ">=3.12"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py312"
