// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Activities;

namespace EduObject.Activities.Guess
{
    [JsonConverter(typeof(GuessItemStateJsonConverter))]
    public enum GuessItemState
    {
        NORMAL,
        HIDDEN,
        CORRECT,
        INCORRECT,
        FILTERED,
        FILTEREDBYUSER,
        FILTEREDBYAGENT
    }

    public class GuessItemStateJsonConverter : JsonConverter<GuessItemState>
    {
        private static readonly Dictionary<string, GuessItemState> StringToEnum = new Dictionary<string, GuessItemState>
        {
            { "N", GuessItemState.NORMAL },        { "H", GuessItemState.HIDDEN },        { "C", GuessItemState.CORRECT },        { "I", GuessItemState.INCORRECT },        { "F", GuessItemState.FILTERED },        { "U", GuessItemState.FILTEREDBYUSER },        { "A", GuessItemState.FILTEREDBYAGENT }    };

        private static readonly Dictionary<GuessItemState, string> EnumToString = new Dictionary<GuessItemState, string>
        {
            { GuessItemState.NORMAL, "N" },        { GuessItemState.HIDDEN, "H" },        { GuessItemState.CORRECT, "C" },        { GuessItemState.INCORRECT, "I" },        { GuessItemState.FILTERED, "F" },        { GuessItemState.FILTEREDBYUSER, "U" },        { GuessItemState.FILTEREDBYAGENT, "A" }    };

        public override void WriteJson(JsonWriter writer, GuessItemState value, JsonSerializer serializer)
        {
            writer.WriteValue(EnumToString[value]);
        }

        public override GuessItemState ReadJson(JsonReader reader, Type objectType, GuessItemState existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            string stringValue = (string)reader.Value;
            return StringToEnum[stringValue];
        }
    }

    [Serializable]
    public class GuessUIData{
        [JsonProperty("question_text")]
        public string QuestionText { get; set; } = "";
        [JsonProperty("used_hints")]
        public List<string> UsedHints { get; set; } = new List<string>();
        [JsonProperty("item_states")]
        public string ItemStates { get; set; } = "";
        [JsonProperty("actionTemplate")]
        public UIAction ActionTemplate { get; set; } = null;
        public GuessUIData(string question_text, List<string> used_hints, string item_states, UIAction actionTemplate)    {
            this.QuestionText = question_text;
            this.UsedHints = used_hints;
            this.ItemStates = item_states;
            this.ActionTemplate = actionTemplate;
        }
        // Parameterless constructor for Unity editor and serialization
        public GuessUIData() { }
    }


}
