# Generated by json_schema_to_code v1.0.1 : json_schema_to_code
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from dataclasses_json import dataclass_json


@dataclass_json
@dataclass(kw_only=True)
class AdditionExercise:
    problem: AdditionExerciseProblem
    state: AdditionExerciseState
    correct_answer: str
    question_text: str
    type: Literal["exercise/maths/basic_operations/addition"] = (
        "exercise/maths/basic_operations/addition"
    )


@dataclass_json
@dataclass(kw_only=True)
class AdditionExerciseProblem:
    operands: list[int]


@dataclass_json
@dataclass(kw_only=True)
class AdditionExerciseState:
    carry_over_row: list[int]
    result_row: list[int]
