// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Activities;

namespace EduObject.Activities.TrueFalse
{
    [Serializable]
    public class TrueFalseUIAnswerOption{
        [JsonProperty("text")]
        public string Text { get; set; } = "";
        [JsonProperty("value")]
        public bool Value { get; set; }
        [JsonProperty("is_correct")]
        public bool IsCorrect { get; set; } = false;
        [JsonProperty("is_selected")]
        public bool IsSelected { get; set; } = false;
        [JsonProperty("action")]
        public UIAction Action { get; set; } = null;
        public TrueFalseUIAnswerOption(string text, bool value, bool is_correct, bool is_selected, UIAction action)    {
            this.Text = text;
            this.Value = value;
            this.IsCorrect = is_correct;
            this.IsSelected = is_selected;
            this.Action = action;
        }
        // Parameterless constructor for Unity editor and serialization
        public TrueFalseUIAnswerOption() { }
    }

    [Serializable]
    public class TrueFalseUIData{
        [JsonProperty("common")]
        public UIDataCommonFields Common { get; set; } = null;
        [JsonProperty("answers")]
        public List<TrueFalseUIAnswerOption> Answers { get; set; } = new List<TrueFalseUIAnswerOption>();
        public TrueFalseUIData(UIDataCommonFields common, List<TrueFalseUIAnswerOption> answers)    {
            this.Common = common;
            this.Answers = answers;
        }
        // Parameterless constructor for Unity editor and serialization
        public TrueFalseUIData() { }
    }


}
