// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Maths.BasicOperations.Activities.Complete;

namespace EduObject.Maths.BasicOperations.Addition.Activities.Complete
{
    [Serializable]
    public class AdditionCompleteUIData{
        [JsonProperty("question_text")]
        public string QuestionText { get; set; } = "";
        [JsonProperty("operand_rows")]
        public List<OperandRowState> OperandRows { get; set; } = new List<OperandRowState>();
        [JsonProperty("carry_over_row")]
        public InputRowState CarryOverRow { get; set; } = null;
        [JsonProperty("result_row")]
        public InputRowState ResultRow { get; set; } = null;
        public AdditionCompleteUIData(string question_text, List<OperandRowState> operand_rows, InputRowState carry_over_row, InputRowState result_row)    {
            this.QuestionText = question_text;
            this.OperandRows = operand_rows;
            this.CarryOverRow = carry_over_row;
            this.ResultRow = result_row;
        }
        // Parameterless constructor for Unity editor and serialization
        public AdditionCompleteUIData() { }
    }


}
