"""
Python AST merger implementation.

Uses Python's built-in ast module to parse, extract custom code,
and merge generated code with existing files.
"""

from __future__ import annotations

import ast
import io
import re
import tokenize

from ..config import MergeStrategy
from .base import AstMerger, CodeMergeError


class PythonAstMerger(AstMerger):
    """Merger for Python source files using the built-in ast module."""

    NO_MERGE_MARKER = "# jstc-no-merge"
    GENERATION_COMMENT_PREFIX = "# Generated by json_schema_to_code"
    # The "class" of a module-level assignment in the (class, name) marker keys.
    MODULE_LEVEL = ""

    # Standard imports that are always generated - don't preserve these
    STANDARD_IMPORTS = {
        ("__future__", "annotations"),
        ("dataclasses", "dataclass"),
        ("dataclasses", "field"),
        ("dataclasses_json", "dataclass_json"),
        ("dataclasses_json", "config"),
        ("typing", "Any"),
        ("typing", "Literal"),
        ("enum", "Enum"),
        ("abc", "ABC"),
    }

    def parse(self, code: str) -> ast.Module:
        """Parse Python source code into an AST.

        Args:
            code: Python source code string

        Returns:
            ast.Module representing the parsed code

        Raises:
            CodeMergeError: If the code cannot be parsed
        """
        try:
            return ast.parse(code)
        except SyntaxError as e:
            raise CodeMergeError(f"Failed to parse Python code: {e}") from e

    def merge_files(
        self,
        generated_code: str,
        existing_code: str,
        merge_strategy: MergeStrategy = MergeStrategy.ERROR,
    ) -> str:
        """Merge generated code into existing file, preserving order.

        Walks the existing file structure and updates elements from generated code:
        classes, imports and module-level type aliases are schema-owned and take the
        generated content where they already stand; new ones are appended (classes,
        imports) or placed where they resolve (aliases). Everything else is kept.
        """
        existing_tree = self.parse(existing_code)
        generated_tree = self.parse(generated_code)
        existing_source_lines = existing_code.splitlines()
        if merge_strategy == MergeStrategy.ERROR:
            self._raise_on_removed_value_members(existing_tree, generated_tree)

        no_merge_fields = self._collect_no_merge_fields(existing_tree, existing_source_lines)
        inline_comments, before_comments = self._extract_comments_for_preservation(existing_code, existing_tree)

        # Build lookups for generated code
        gen_imports = self._get_imports_list(generated_tree)
        gen_classes = {n.name: n for n in generated_tree.body if isinstance(n, ast.ClassDef)}

        new_body = []
        seen_imports = set()  # Full import statements (for plain imports)
        module_imports: dict[str, ast.ImportFrom] = {}  # module -> ImportFrom node

        # Walk existing tree in order
        for node in existing_tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                if isinstance(node, ast.ImportFrom) and node.module:
                    if node.module in module_imports:
                        # Already have import from this module - merge names into existing
                        new_names = self._get_imported_names(node)
                        self._merge_import_names(module_imports[node.module], new_names)
                        # Don't add duplicate import to new_body
                    else:
                        # First import from this module
                        new_body.append(node)
                        module_imports[node.module] = node
                else:
                    # Plain import - use string comparison
                    unparsed = ast.unparse(node)
                    if unparsed not in seen_imports:
                        new_body.append(node)
                        seen_imports.add(unparsed)

            elif isinstance(node, ast.ClassDef):
                if node.name in gen_classes:
                    merged = self._merge_class(node, gen_classes[node.name], merge_strategy, existing_source_lines)
                    new_body.append(merged)
                    del gen_classes[node.name]
                else:
                    # Custom class, keep as-is
                    new_body.append(node)

            else:
                # Other elements (docstrings, constants, etc.)
                new_body.append(node)

        # Add new imports from generated (merge with existing or add new)
        insert_idx = self._find_import_insert_index_in_list(new_body)
        for imp in gen_imports:
            if isinstance(imp, ast.ImportFrom) and imp.module:
                # ImportFrom - merge names with existing import from same module
                if imp.module in module_imports:
                    # Merge new names into existing import
                    new_names = self._get_imported_names(imp)
                    self._merge_import_names(module_imports[imp.module], new_names)
                else:
                    # __future__ imports must always be first
                    if imp.module == "__future__":
                        new_body.insert(0, imp)
                        module_imports[imp.module] = imp
                        insert_idx += 1
                    else:
                        new_body.insert(insert_idx, imp)
                        module_imports[imp.module] = imp
                        insert_idx += 1
            else:
                # Plain import - use string comparison
                if ast.unparse(imp) not in seen_imports:
                    new_body.insert(insert_idx, imp)
                    seen_imports.add(ast.unparse(imp))
                    insert_idx += 1

        # Add new classes from generated at end
        new_class_names = set(gen_classes)
        for node in generated_tree.body:
            if isinstance(node, ast.ClassDef) and node.name in new_class_names:
                new_body.append(node)

        # Module-level assignments (chiefly union type aliases) are schema-owned like
        # classes: one the file already has is updated where it stands, a new one is
        # inserted. Either way it must sit below every definition it references --
        # `A | B` evaluates eagerly, so an alias above a class it unions is a NameError,
        # not merely an F821 -- so an alias that gained a member defined further down
        # (a class new in this generation was just appended) moves down to it.
        for node in generated_tree.body:
            if not isinstance(node, (ast.Assign, ast.AnnAssign)):
                continue
            names = self._assign_target_names(node)
            if not names or any((self.MODULE_LEVEL, name) in no_merge_fields for name in names):
                # A marked alias is hand-owned (e.g. a union whose member order the
                # file pins because dataclasses_json decodes members in that order).
                continue
            current = next((i for i, placed in enumerate(new_body) if self._assign_target_names(placed) & names), None)
            if current is not None:
                del new_body[current]
            referenced = {n.id for n in ast.walk(node) if isinstance(n, ast.Name)} - names
            last_dependency = None
            for index, placed in enumerate(new_body):
                defines = {placed.name} if isinstance(placed, ast.ClassDef) else self._assign_target_names(placed)
                if defines & referenced:
                    last_dependency = index
            if current is None:
                insert_at = len(new_body) if last_dependency is None else last_dependency + 1
            elif last_dependency is None or current > last_dependency:
                insert_at = current
            else:
                insert_at = last_dependency + 1
            new_body.insert(insert_at, node)

        existing_tree.body = new_body
        ast.fix_missing_locations(existing_tree)
        merged_code = ast.unparse(existing_tree)

        if inline_comments or before_comments:
            merged_code = self._restore_preserved_comments(merged_code, inline_comments, before_comments)

        if no_merge_fields:
            merged_code = self._restore_no_merge_markers(merged_code, no_merge_fields)

        return merged_code

    def _raise_on_removed_value_members(self, existing_tree: ast.Module, generated_tree: ast.Module) -> None:
        """Raise when existing classes contain value members removed from generated code."""
        existing_classes = {node.name: node for node in existing_tree.body if isinstance(node, ast.ClassDef)}
        generated_classes = {node.name: node for node in generated_tree.body if isinstance(node, ast.ClassDef)}

        for class_name, existing_class in existing_classes.items():
            generated_class = generated_classes.get(class_name)
            if generated_class is None:
                continue

            generated_members = self._get_class_value_members(generated_class)
            for member_name, member_node in self._get_class_value_members(existing_class).items():
                if member_name in generated_members:
                    continue
                line = getattr(member_node, "lineno", "?")
                col = getattr(member_node, "col_offset", "?")
                raise CodeMergeError(
                    "Merge aborted: existing value member is not generated anymore. "
                    "Use --merge-strategy merge to keep it, or --merge-strategy delete to remove it. "
                    f"Location: class '{class_name}', member '{member_name}' at line {line}, column {col}."
                )

    @staticmethod
    def _assign_target_names(node: ast.AST) -> set[str]:
        """Top-level names bound by an assignment (module-level type aliases, constants)."""
        if isinstance(node, ast.AnnAssign):
            return {node.target.id} if isinstance(node.target, ast.Name) else set()
        if isinstance(node, ast.Assign):
            return {t.id for t in node.targets if isinstance(t, ast.Name)}
        return set()

    def _get_class_value_members(self, class_node: ast.ClassDef) -> dict[str, ast.AST]:
        """Return class value members (fields/constants), excluding functions."""
        members: dict[str, ast.AST] = {}
        for item in class_node.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                members[item.target.id] = item
                continue
            if isinstance(item, ast.Assign):
                if len(item.targets) != 1:
                    continue
                target = item.targets[0]
                if isinstance(target, ast.Name):
                    members[target.id] = item
        return members

    def _has_no_merge_marker(self, source_lines: list[str], node: ast.stmt) -> bool:
        """Whether any source line of the node carries the jstc-no-merge marker.

        A class field is one line; a module-level alias may span several once a
        formatter has wrapped it, with the marker on whichever line it landed.
        """
        first, last = node.lineno - 1, (node.end_lineno or node.lineno) - 1
        return any(self.NO_MERGE_MARKER in source_lines[i] for i in range(max(first, 0), min(last, len(source_lines) - 1) + 1))

    def _collect_no_merge_fields(self, tree: ast.Module, source_lines: list[str]) -> set[tuple[str, str]]:
        """(class_name, name) pairs carrying the marker; MODULE_LEVEL stands for the module."""
        result: set[tuple[str, str]] = set()
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                for item in node.body:
                    if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name) and self._has_no_merge_marker(source_lines, item):
                        result.add((node.name, item.target.id))
            elif isinstance(node, (ast.Assign, ast.AnnAssign)) and self._has_no_merge_marker(source_lines, node):
                result |= {(self.MODULE_LEVEL, name) for name in self._assign_target_names(node)}
        return result

    _MODULE_ASSIGN_LINE = re.compile(r"([A-Za-z_]\w*)\s*[:=]")

    def _restore_no_merge_markers(self, code: str, no_merge_fields: set[tuple[str, str]]) -> str:
        """Re-inject # jstc-no-merge comments on fields that had them.

        ast.unparse() strips all comments, so we need to re-add them after unparse.
        """
        lines = code.splitlines()
        current_class: str | None = None

        for i, line in enumerate(lines):
            stripped = line.lstrip()
            if stripped.startswith("class "):
                paren = stripped.find("(")
                colon = stripped.find(":")
                end = paren if paren != -1 and (colon == -1 or paren < colon) else colon
                if end != -1:
                    current_class = stripped[len("class ") : end].strip()
            elif line and not line[0].isspace():
                # Back at module level: a class body cannot reach column 0.
                current_class = None
                if not stripped.startswith(("def ", "@", "#")):
                    match = self._MODULE_ASSIGN_LINE.match(stripped)
                    if match and (self.MODULE_LEVEL, match.group(1)) in no_merge_fields:
                        lines[i] = line + "  " + self.NO_MERGE_MARKER
            elif current_class and ":" in stripped and not stripped.startswith(("def ", "class ", "@", "#")):
                field_name = stripped.split(":")[0].strip()
                if (current_class, field_name) in no_merge_fields:
                    lines[i] = line + "  " + self.NO_MERGE_MARKER

        return "\n".join(lines)

    # -- Comment preservation --

    def _extract_comments_for_preservation(
        self,
        source: str,
        tree: ast.Module,
    ) -> tuple[list[tuple[tuple[str, str], str]], list[tuple[tuple[str, str], list[str]]]]:
        """Extract comments from existing source for restoration after ast.unparse().

        Returns:
            inline_comments: list of ((class_context, normalized_code), comment_text)
            before_comments: list of ((class_context, normalized_code), comment_lines)
        """
        source_lines = source.splitlines()
        class_ranges = self._build_class_line_ranges(tree)

        comment_line_set: set[int] = set()
        inline_data: dict[int, str] = {}

        try:
            tokens = list(tokenize.generate_tokens(io.StringIO(source).readline))
            for tok in tokens:
                if tok.type != tokenize.COMMENT:
                    continue
                if self.NO_MERGE_MARKER in tok.string:
                    continue
                if tok.string.startswith(self.GENERATION_COMMENT_PREFIX):
                    continue
                line_no = tok.start[0]
                col = tok.start[1]
                code_before = source_lines[line_no - 1][:col].rstrip()
                if code_before:
                    inline_data[line_no] = tok.string
                else:
                    comment_line_set.add(line_no)
        except tokenize.TokenError:
            return [], []

        inline_comments: list[tuple[tuple[str, str], str]] = []
        for line_no, comment_text in sorted(inline_data.items()):
            line = source_lines[line_no - 1]
            code_part = line[: line.index(comment_text)].rstrip()
            class_ctx = self._class_at_line(class_ranges, line_no)
            key = (class_ctx, self._normalize_code_for_matching(code_part))
            inline_comments.append((key, comment_text))

        before_comments: list[tuple[tuple[str, str], list[str]]] = []
        i = 0
        while i < len(source_lines):
            line_no = i + 1
            if line_no in comment_line_set:
                block = [source_lines[i]]
                i += 1
                while i < len(source_lines):
                    next_ln = i + 1
                    if next_ln in comment_line_set:
                        block.append(source_lines[i])
                        i += 1
                    elif not source_lines[i].strip():
                        block.append(source_lines[i])
                        i += 1
                    else:
                        break
                while block and not block[-1].strip():
                    block.pop()
                # Skip blank lines to find next code line
                while i < len(source_lines) and not source_lines[i].strip():
                    i += 1
                if i < len(source_lines) and block:
                    next_code = source_lines[i]
                    class_ctx = self._class_at_line(class_ranges, i + 1)
                    key = (class_ctx, self._normalize_code_for_matching(next_code))
                    before_comments.append((key, block))
            else:
                i += 1

        return inline_comments, before_comments

    def _restore_preserved_comments(
        self,
        merged_code: str,
        inline_comments: list[tuple[tuple[str, str], str]],
        before_comments: list[tuple[tuple[str, str], list[str]]],
    ) -> str:
        """Re-inject preserved comments into merged code."""
        try:
            merged_tree = ast.parse(merged_code)
        except SyntaxError:
            return merged_code

        merged_ranges = self._build_class_line_ranges(merged_tree)
        merged_lines = merged_code.splitlines()

        merged_keys = []
        for i, line in enumerate(merged_lines):
            class_ctx = self._class_at_line(merged_ranges, i + 1)
            normalized = self._normalize_code_for_matching(line)
            merged_keys.append((class_ctx, normalized))

        inline_used = [False] * len(inline_comments)
        before_used = [False] * len(before_comments)
        line_inline: dict[int, str] = {}
        line_before: dict[int, list[str]] = {}

        for i, key in enumerate(merged_keys):
            if not key[1].strip():
                continue
            for j, (ik, comment) in enumerate(inline_comments):
                if not inline_used[j] and ik == key:
                    line_inline[i] = comment
                    inline_used[j] = True
                    break
            for j, (bk, block) in enumerate(before_comments):
                if not before_used[j] and bk == key:
                    line_before[i] = block
                    before_used[j] = True
                    break

        result: list[str] = []
        for i, line in enumerate(merged_lines):
            if i in line_before:
                result.extend(line_before[i])
            if i in line_inline:
                result.append(line + "  " + line_inline[i])
            else:
                result.append(line)

        return "\n".join(result)

    def _build_class_line_ranges(self, tree: ast.Module) -> list[tuple[str, int, int]]:
        """Build (class_name, start_line, end_line) list from the AST."""
        ranges: list[tuple[str, int, int]] = []
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                start = node.decorator_list[0].lineno if node.decorator_list else node.lineno
                ranges.append((node.name, start, node.end_lineno))
        return ranges

    def _class_at_line(self, ranges: list[tuple[str, int, int]], line_no: int) -> str:
        """Return the class name containing line_no, or '' for module level."""
        for name, start, end in ranges:
            if start <= line_no <= end:
                return name
        return ""

    def _normalize_code_for_matching(self, line: str) -> str:
        """Normalize a code line for matching between original and unparsed code."""
        return " ".join(line.split())

    @staticmethod
    def _same_annotation(generated: ast.AnnAssign, existing: ast.AnnAssign) -> bool:
        """Whether two field declarations carry the same type annotation."""
        try:
            return ast.unparse(generated.annotation) == ast.unparse(existing.annotation)
        except (AttributeError, ValueError):
            return False

    def _has_field_metadata(self, node: ast.AnnAssign) -> bool:
        """Check if a field uses field() with a metadata= keyword argument."""
        if node.value is None or not isinstance(node.value, ast.Call):
            return False
        func = node.value.func
        if isinstance(func, ast.Name) and func.id == "field":
            return any(kw.arg == "metadata" for kw in node.value.keywords)
        return False

    def _merge_class(
        self,
        existing: ast.ClassDef,
        generated: ast.ClassDef,
        merge_strategy: MergeStrategy,
        existing_source_lines: list[str],
    ) -> ast.ClassDef:
        """Merge a class: preserve existing order, update content from generated."""
        gen_fields = {}
        gen_methods = {}
        for item in generated.body:
            if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                gen_fields[item.target.id] = item
            elif isinstance(item, ast.FunctionDef):
                gen_methods[item.name] = item

        new_body = []
        seen_fields = set()
        seen_methods = set()

        for item in existing.body:
            if isinstance(item, ast.Expr) and isinstance(item.value, ast.Constant):
                new_body.append(item)

            elif isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                field_name = item.target.id
                if field_name in gen_fields:
                    if self._has_no_merge_marker(existing_source_lines, item):
                        new_body.append(item)
                    elif self._has_field_metadata(item):
                        new_body.append(item)
                    else:
                        gen_field = gen_fields[field_name]
                        # A generated field's default is schema-owned: the generated declaration wins
                        # outright (express a default in the schema, not by hand in this file).
                        new_body.append(gen_field)
                elif merge_strategy != MergeStrategy.DELETE:
                    new_body.append(item)
                seen_fields.add(field_name)

            elif isinstance(item, ast.FunctionDef):
                method_name = item.name
                if method_name in gen_methods:
                    # Merge method: keep docstring, use generated body
                    merged = self._merge_method(item, gen_methods[method_name])
                    new_body.append(merged)
                else:
                    # Custom method, keep as-is
                    new_body.append(item)
                seen_methods.add(method_name)

            else:
                # Other items (Assign, etc.)
                new_body.append(item)

        # Add new fields from generated (at end of fields section)
        field_insert_idx = self._find_field_insert_index(new_body)
        for name, field in gen_fields.items():
            if name not in seen_fields:
                new_body.insert(field_insert_idx, field)
                field_insert_idx += 1

        # Add new methods from generated at end
        for name, method in gen_methods.items():
            if name not in seen_methods:
                new_body.append(method)

        existing.body = new_body
        # Bases and decorators come from the schema, like the fields. A hand-added
        # decorator survives; a generated one (dataclass, dataclass_json) is taken from
        # the generated class, so a change in how classes are decorated -- kw_only, a
        # base that gained its decorators -- reaches files generated before it instead
        # of being masked by the merge forever.
        existing.bases = generated.bases
        generated_decorators = {self._decorator_name(d) for d in generated.decorator_list}
        existing.decorator_list = generated.decorator_list + [d for d in existing.decorator_list if self._decorator_name(d) not in generated_decorators]
        return existing

    @staticmethod
    def _decorator_name(decorator: ast.expr) -> str:
        """The decorator's identity: `dataclass(kw_only=True)` and `dataclass` are the same one."""
        return ast.unparse(decorator.func if isinstance(decorator, ast.Call) else decorator)

    def _merge_method(self, existing: ast.FunctionDef, generated: ast.FunctionDef) -> ast.FunctionDef:
        """Merge a method: keep existing docstring, use generated body."""
        existing_docstring = ast.get_docstring(existing)

        # Use generated method as base
        result = generated

        # Restore docstring if it existed
        if existing_docstring:
            has_docstring = result.body and isinstance(result.body[0], ast.Expr) and isinstance(result.body[0].value, ast.Constant) and isinstance(result.body[0].value.value, str)
            if not has_docstring:
                docstring_node = ast.Expr(value=ast.Constant(value=existing_docstring))
                result.body.insert(0, docstring_node)

        return result

    def _get_imports_list(self, tree: ast.Module) -> list:
        """Get list of import nodes."""
        return [n for n in tree.body if isinstance(n, (ast.Import, ast.ImportFrom))]

    def _get_import_key(self, node: ast.ImportFrom) -> str | None:
        """Get the module key for an ImportFrom node."""
        if isinstance(node, ast.ImportFrom) and node.module:
            return node.module
        return None

    def _get_imported_names(self, node: ast.ImportFrom) -> set[str]:
        """Get set of names imported from an ImportFrom node."""
        if isinstance(node, ast.ImportFrom):
            return {alias.name for alias in node.names}
        return set()

    def _merge_import_names(self, existing: ast.ImportFrom, new_names: set[str]) -> ast.ImportFrom:
        """Add new names to an existing ImportFrom node."""
        existing_names = {alias.name for alias in existing.names}
        all_names = existing_names | new_names
        # Sort for consistent output
        sorted_names = sorted(all_names)
        existing.names = [ast.alias(name=n, asname=None) for n in sorted_names]
        return existing

    def _find_import_insert_index_in_list(self, body: list) -> int:
        """Find index after last import in a body list."""
        last_idx = 0
        for i, node in enumerate(body):
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                last_idx = i + 1
        return last_idx

    def _find_field_insert_index(self, body: list) -> int:
        """Find index after last field (before first method)."""
        last_field_idx = 0
        for i, item in enumerate(body):
            if isinstance(item, (ast.AnnAssign, ast.Assign)):
                last_field_idx = i + 1
            elif isinstance(item, ast.Expr):
                # Docstring at start
                last_field_idx = i + 1
            elif isinstance(item, ast.FunctionDef):
                break
        return last_field_idx

    def validate(self, code: str) -> None:
        """Validate that merged Python code is syntactically correct.

        Args:
            code: The merged code to validate

        Raises:
            CodeMergeError: If validation fails
        """
        try:
            ast.parse(code)
        except SyntaxError as e:
            raise CodeMergeError(f"Merged code is not valid Python: {e}") from e
