"""
Pipeline generator that orchestrates all phases.

This is the main entry point for the new pipeline-based code generation.
"""

from __future__ import annotations

from typing import Any

from .. import __version__
from ..cli_utils import reconstruct_command_line
from .analyzer import SchemaAnalyzer
from .backends import CodeBackend, CSharpBackend, PythonBackend
from .config import CodeGeneratorConfig
from .schema_ast import SchemaParser


class PipelineGenerator:
    """
    Pipeline-based code generator.

    Orchestrates the three phases:
    1. Parse JSON Schema to AST
    2. Analyze AST and build IR
    3. Generate code using language-specific backend
    """

    def __init__(
        self,
        class_name: str,
        schema: dict[str, Any],
        config: CodeGeneratorConfig,
        language: str,
    ):
        """
        Initialize the generator.

        Args:
            class_name: Name for the root class
            schema: The JSON Schema dictionary
            config: Code generation configuration
            language: Target language ("python" or "cs")
        """
        self.class_name = class_name
        self.schema = schema
        self.config = config
        self.language = language

        # Initialize components
        self.parser = SchemaParser()
        self.analyzer = SchemaAnalyzer(language, config)
        self.backend = self._create_backend()

    def _create_backend(self) -> CodeBackend:
        """Create the appropriate backend for the language."""
        if self.language == "python":
            return PythonBackend(self.config)
        elif self.language == "cs":
            return CSharpBackend(self.config)
        else:
            raise ValueError(f"Unsupported language: {self.language}")

    def generate(self) -> str:
        """
        Generate code using the pipeline.

        Returns:
            Generated code as a string
        """
        # Phase 1: Parse schema to AST
        ast = self.parser.parse(self.schema, self.class_name)

        # Phase 2: Analyze AST and build IR
        ir = self.analyzer.analyze(ast)

        # Set generation comment
        ir.generation_comment = self._generate_comment()

        # Phase 3: Generate code
        return self.backend.generate(ir)

    def _generate_comment(self) -> str:
        """Generate the file header comment."""
        if not self.config.add_generation_comment:
            return ""

        comment_prefix = "#" if self.language == "python" else "//"

        try:
            from ..json_schema_to_code import json_schema_to_code as click_command

            command_line = reconstruct_command_line(click_command)
        except (ImportError, AttributeError, RuntimeError):
            command_line = "json_schema_to_code"

        return f"{comment_prefix} Generated by json_schema_to_code v{__version__} : {command_line}"
