# Generated by json_schema_to_code v1.0.1 : json_schema_to_code
from __future__ import annotations

from dataclasses import dataclass

from dataclasses_json import dataclass_json


@dataclass_json
@dataclass(kw_only=True)
class Classify:
    problem: ClassifyProblem
    state: ClassifyState


@dataclass_json
@dataclass(kw_only=True)
class Object:
    type: str
    uuid: str


@dataclass_json
@dataclass(kw_only=True)
class ClassifiableObject:
    object: Object
    bucket: str


@dataclass_json
@dataclass(kw_only=True)
class ClassifyProblem:
    buckets: list[ClassifyProblemBuckets]
    items: list[ClassifiableObject]


@dataclass_json
@dataclass(kw_only=True)
class ClassifyProblemBuckets:
    name: str
    description: str


@dataclass_json
@dataclass(kw_only=True)
class ClassifyState:
    buckets: list[ClassifyStateBuckets]
    items: list[ClassifiableObject]


@dataclass_json
@dataclass(kw_only=True)
class ClassifyStateBuckets:
    name: str
    items: list[ClassifiableObject]
