// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Maths.BasicOperations.Activities.Complete;
using EduObject.Activities;

namespace EduObject.Maths.BasicOperations.Activities.Complete
{
    [Serializable]
    public class DigitState{
        [JsonProperty("text")]
        public string Text { get; set; }
        [JsonProperty("color_flag")]
        public string ColorFlag { get; set; } = "normal";
        [JsonProperty("interaction")]
        public string Interaction { get; set; } = "ReadOnly";
        [JsonProperty("action")]
        public UIAction? Action { get; set; }
        public DigitState(string text, string color_flag, string interaction, UIAction? action)    {
            this.Text = text;
            this.ColorFlag = color_flag;
            this.Interaction = interaction;
            this.Action = action;
        }
        // Parameterless constructor for Unity editor and serialization
        public DigitState() { }
    }

    [Serializable]
    public class OperandRowState{
        [JsonProperty("digits")]
        public List<DigitState> Digits { get; set; }
        public OperandRowState(List<DigitState> digits)    {
            this.Digits = digits;
        }
        // Parameterless constructor for Unity editor and serialization
        public OperandRowState() { }
    }

    [Serializable]
    public class InputRowState{
        [JsonProperty("digits")]
        public List<DigitState> Digits { get; set; }
        public InputRowState(List<DigitState> digits)    {
            this.Digits = digits;
        }
        // Parameterless constructor for Unity editor and serialization
        public InputRowState() { }
    }


}
