// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using JsonSubTypes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
[Serializable]
public class Geometry{
    [JsonProperty("objects")]
    public List<GeometryObject> Objects { get; set; }
    [JsonProperty("constraints")]
    public List<Constraint> Constraints { get; set; }
    [JsonProperty("styles")]
    public List<Style> Styles { get; set; }
    public Geometry(List<GeometryObject> objects, List<Constraint> constraints, List<Style> styles)    {
        this.Objects = objects;
        this.Constraints = constraints;
        this.Styles = styles;
    }
    // Parameterless constructor for Unity editor and serialization
    public Geometry() { }
}

[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectPoint), "point")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectSegment), "segment")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectLine), "line")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectRay), "ray")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectVector), "vector")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectTriangle), "triangle")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectQuadrilateral), "quadrilateral")]
[JsonSubtypes.KnownSubType(typeof(GeometryObjectCircle), "center")]
public class GeometryObject{
    [JsonProperty("type")]
    public string Type { get; set; }
    public GeometryObject(string type)    {
        this.Type = type;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObject() { }
}

[Serializable]
public class GeometryObjectPoint : GeometryObject{
    [JsonProperty("type")]
    public const string type = "point";
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("coordinate")]
    public List<float>? Coordinate { get; set; }
    public GeometryObjectPoint(string name, List<float>? coordinate): base("point")
    {
        this.Name = name;
        this.Coordinate = coordinate;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectPoint() { }
}

[Serializable]
public class GeometryObjectSegment : GeometryObject{
    [JsonProperty("type")]
    public const string type = "segment";
    [JsonProperty("points")]
    public List<string> Points { get; set; }
    public GeometryObjectSegment(List<string> points): base("segment")
    {
        this.Points = points;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectSegment() { }
}

[Serializable]
public class GeometryObjectLine : GeometryObject{
    [JsonProperty("type")]
    public const string type = "line";
    [JsonProperty("points")]
    public List<string>? Points { get; set; }
    public GeometryObjectLine(List<string>? points): base("line")
    {
        this.Points = points;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectLine() { }
}

[Serializable]
public class GeometryObjectRay : GeometryObject{
    [JsonProperty("type")]
    public const string type = "ray";
    [JsonProperty("points")]
    public List<string> Points { get; set; }
    public GeometryObjectRay(List<string> points): base("ray")
    {
        this.Points = points;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectRay() { }
}

[Serializable]
public class GeometryObjectVector : GeometryObject{
    [JsonProperty("type")]
    public const string type = "vector";
    [JsonProperty("points")]
    public List<string> Points { get; set; }
    public GeometryObjectVector(List<string> points): base("vector")
    {
        this.Points = points;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectVector() { }
}

[Serializable]
public class GeometryObjectTriangle : GeometryObject{
    [JsonProperty("type")]
    public const string type = "triangle";
    [JsonProperty("kind")]
    public string Kind { get; set; }  // Allowed values: "isosceles", "equilateral", "general"
    [JsonProperty("points")]
    public List<string> Points { get; set; }
    public GeometryObjectTriangle(string kind, List<string> points): base("triangle")
    {
        this.Kind = kind;
        this.Points = points;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectTriangle() { }
}

[Serializable]
public class GeometryObjectQuadrilateral : GeometryObject{
    [JsonProperty("type")]
    public const string type = "quadrilateral";
    [JsonProperty("kind")]
    public string Kind { get; set; }  // Allowed values: "square", "rectangle", "rhombus", "parallelogram", "trapezoid", "kite", "general"
    [JsonProperty("points")]
    public List<string>? Points { get; set; }
    public GeometryObjectQuadrilateral(string kind, List<string>? points): base("quadrilateral")
    {
        this.Kind = kind;
        this.Points = points;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectQuadrilateral() { }
}

[Serializable]
public class GeometryObjectCircle : GeometryObject{
    [JsonProperty("type")]
    public const string type = "center";
    [JsonProperty("center")]
    public string Center { get; set; }
    [JsonProperty("radius")]
    public float Radius { get; set; }
    public GeometryObjectCircle(string center, float radius): base("center")
    {
        this.Center = center;
        this.Radius = radius;
    }
    // Parameterless constructor for Unity editor and serialization
    public GeometryObjectCircle() { }
}

[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(ConstraintDistanceFixed), "distance_fixed")]
[JsonSubtypes.KnownSubType(typeof(ConstraintDistanceEquals), "distance_equals")]
[JsonSubtypes.KnownSubType(typeof(ConstraintAngleFixed), "angle_fixed")]
[JsonSubtypes.KnownSubType(typeof(ConstraintAngleEquals), "angle_equals")]
public class Constraint{
    [JsonProperty("type")]
    public string Type { get; set; }
    public Constraint(string type)    {
        this.Type = type;
    }
    // Parameterless constructor for Unity editor and serialization
    public Constraint() { }
}

[Serializable]
public class ConstraintDistanceFixed : Constraint{
    [JsonProperty("type")]
    public const string type = "distance_fixed";
    [JsonProperty("distance")]
    public float Distance { get; set; }
    public ConstraintDistanceFixed(float distance): base("distance_fixed")
    {
        this.Distance = distance;
    }
    // Parameterless constructor for Unity editor and serialization
    public ConstraintDistanceFixed() { }
}

[Serializable]
public class ConstraintDistanceEquals : Constraint{
    [JsonProperty("type")]
    public const string type = "distance_equals";
    public ConstraintDistanceEquals(): base("distance_equals")
    {
    }
}

[Serializable]
public class ConstraintAngleFixed : Constraint{
    [JsonProperty("type")]
    public const string type = "angle_fixed";
    [JsonProperty("angle")]
    public float Angle { get; set; }
    public ConstraintAngleFixed(float angle): base("angle_fixed")
    {
        this.Angle = angle;
    }
    // Parameterless constructor for Unity editor and serialization
    public ConstraintAngleFixed() { }
}

[Serializable]
public class ConstraintAngleEquals : Constraint{
    [JsonProperty("type")]
    public const string type = "angle_equals";
    public ConstraintAngleEquals(): base("angle_equals")
    {
    }
}

[Serializable]
public class Style{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("color")]
    public string Color { get; set; }
    [JsonProperty("strokeWidth")]
    public float StrokeWidth { get; set; }
    public Style(string name, string color, float strokeWidth)    {
        this.Name = name;
        this.Color = color;
        this.StrokeWidth = strokeWidth;
    }
    // Parameterless constructor for Unity editor and serialization
    public Style() { }
}
