import json
from pathlib import Path
from unittest import TestCase

from json_schema_to_code.codegen import CodeGenerator, CodeGeneratorConfig


class TestGenerationComment(TestCase):
    """Test generation comment functionality"""

    def setUp(self):
        self.test_data_path = Path(__file__).parent / "test_data" / "generation_comment_tests.json"
        with open(self.test_data_path) as f:
            self.test_cases = json.load(f)

    def _generate_code(self, schema, config_dict):
        """Helper to generate code with given schema and config"""
        config = CodeGeneratorConfig()
        for key, value in config_dict.items():
            setattr(config, key, value)

        codegen = CodeGenerator("TestSchema", schema, config, "python")
        return codegen.generate()

    def test_generation_comment_enabled(self):
        """Test that generation comment is added when enabled"""
        test_case = next(tc for tc in self.test_cases if tc["name"] == "generation_comment_enabled")

        generated_code = self._generate_code(test_case["schema"], test_case["config"])

        # Check expected content is present
        for expected in test_case["expected_contains"]:
            self.assertIn(
                expected, generated_code, f"Expected '{expected}' not found in generated code"
            )

        # Check generation comment is at the top
        lines = generated_code.split("\n")
        self.assertTrue(
            lines[0].startswith("# Generated by json_schema_to_code"),
            "Generation comment should be the first line",
        )

    def test_generation_comment_disabled(self):
        """Test that generation comment is not added when disabled"""
        test_case = next(
            tc for tc in self.test_cases if tc["name"] == "generation_comment_disabled"
        )

        generated_code = self._generate_code(test_case["schema"], test_case["config"])

        # Check expected content is present
        for expected in test_case["expected_contains"]:
            self.assertIn(
                expected, generated_code, f"Expected '{expected}' not found in generated code"
            )

        # Check unwanted content is not present
        for not_expected in test_case["expected_not_contains"]:
            self.assertNotIn(
                not_expected, generated_code, f"Unwanted '{not_expected}' found in generated code"
            )

        # Check that first line is not a comment
        lines = generated_code.split("\n")
        first_non_empty = next(line for line in lines if line.strip())
        self.assertFalse(
            first_non_empty.startswith("#"),
            "First line should not be a comment when generation comment is disabled",
        )

    def test_all_generation_comment_cases(self):
        """Run all generation comment test cases"""
        for test_case in self.test_cases:
            with self.subTest(test_case=test_case["name"]):
                generated_code = self._generate_code(test_case["schema"], test_case["config"])

                # Check expected content is present
                for expected in test_case["expected_contains"]:
                    self.assertIn(
                        expected,
                        generated_code,
                        f"Test '{test_case['name']}': Expected '{expected}' not found",
                    )

                # Check unwanted content is not present
                for not_expected in test_case["expected_not_contains"]:
                    self.assertNotIn(
                        not_expected,
                        generated_code,
                        f"Test '{test_case['name']}': Unwanted '{not_expected}' found",
                    )


if __name__ == "__main__":
    import pytest

    pytest.main([__file__])
