// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;

namespace EduObject.Primitive.Statement
{
    [Serializable]
    public class StatementDataStatement{
        [JsonProperty("text")]
        public string Text { get; set; }
        public StatementDataStatement(string text)    {
            this.Text = text;
        }
        // Parameterless constructor for Unity editor and serialization
        public StatementDataStatement() { }
    }

    [Serializable]
    public class StatementData{
        [JsonProperty("type")]
        public const string type = "primitive/statement";
        [JsonProperty("statement")]
        public StatementDataStatement Statement { get; set; }
        public StatementData(StatementDataStatement statement)    {
            this.Statement = statement;
        }
        // Parameterless constructor for Unity editor and serialization
        public StatementData() { }
    }


}
