// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Activities;

namespace EduObject.Activities.Classify
{
    [Serializable]
    public class ClassifyInnerObject{
        [JsonProperty("type")]
        public string Type { get; set; }
        [JsonProperty("uuid")]
        public string Uuid { get; set; }
        [JsonProperty("text")]
        public string Text { get; set; } = null;
        [JsonProperty("image_url")]
        public string ImageUrl { get; set; } = null;
        [JsonProperty("hint")]
        public string Hint { get; set; } = null;
        [JsonProperty("explanation")]
        public string Explanation { get; set; } = null;
        [JsonProperty("mnemonic")]
        public string Mnemonic { get; set; } = null;
        [JsonProperty("additional_properties")]
        public object AdditionalProperties { get; set; } = new object();
        public ClassifyInnerObject(string type, string uuid, string text, string image_url, string hint, string explanation, string mnemonic, object additional_properties)    {
            this.Type = type;
            this.Uuid = uuid;
            this.Text = text;
            this.ImageUrl = image_url;
            this.Hint = hint;
            this.Explanation = explanation;
            this.Mnemonic = mnemonic;
            this.AdditionalProperties = additional_properties;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyInnerObject() { }
    }

    [Serializable]
    public class ClassifiableObject{
        [JsonProperty("object")]
        public ClassifyInnerObject Object { get; set; }
        [JsonProperty("bucket")]
        public string Bucket { get; set; }
        public ClassifiableObject(ClassifyInnerObject @object, string bucket)    {
            this.Object = @object;
            this.Bucket = bucket;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifiableObject() { }
    }

    [Serializable]
    public class ClassifyUIData{
        [JsonProperty("buckets")]
        public List<ClassifyBucket> Buckets { get; set; }
        [JsonProperty("items")]
        public List<ClassifiableObject> Items { get; set; }
        [JsonProperty("classified_items")]
        public List<ClassifyStateBucket> ClassifiedItems { get; set; }
        [JsonProperty("actionTemplate")]
        public UIAction ActionTemplate { get; set; }
        public ClassifyUIData(List<ClassifyBucket> buckets, List<ClassifiableObject> items, List<ClassifyStateBucket> classified_items, UIAction actionTemplate)    {
            this.Buckets = buckets;
            this.Items = items;
            this.ClassifiedItems = classified_items;
            this.ActionTemplate = actionTemplate;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyUIData() { }
    }

    [Serializable]
    public class ClassifyBucket{
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("description")]
        public string Description { get; set; }
        public ClassifyBucket(string name, string description)    {
            this.Name = name;
            this.Description = description;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyBucket() { }
    }

    [Serializable]
    public class ClassifyStateBucket{
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("items")]
        public List<ClassifiableObject> Items { get; set; }
        public ClassifyStateBucket(string name, List<ClassifiableObject> items)    {
            this.Name = name;
            this.Items = items;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyStateBucket() { }
    }

    [Serializable]
    public class ClassifyProblem{
        [JsonProperty("buckets")]
        public List<ClassifyBucket> Buckets { get; set; }
        [JsonProperty("items")]
        public List<ClassifiableObject> Items { get; set; }
        public ClassifyProblem(List<ClassifyBucket> buckets, List<ClassifiableObject> items)    {
            this.Buckets = buckets;
            this.Items = items;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyProblem() { }
    }

    [Serializable]
    public class ClassifyState{
        [JsonProperty("buckets")]
        public List<ClassifyStateBucket> Buckets { get; set; }
        [JsonProperty("items")]
        public List<ClassifiableObject> Items { get; set; }
        public ClassifyState(List<ClassifyStateBucket> buckets, List<ClassifiableObject> items)    {
            this.Buckets = buckets;
            this.Items = items;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyState() { }
    }

    [Serializable]
    public class ClassifyData{
        [JsonProperty("problem")]
        public ClassifyProblem Problem { get; set; } = null;
        [JsonProperty("state")]
        public ClassifyState State { get; set; } = null;
        [JsonProperty("ui_data")]
        public ClassifyUIData UiData { get; set; } = null;
        public ClassifyData(ClassifyProblem problem, ClassifyState state, ClassifyUIData ui_data)    {
            this.Problem = problem;
            this.State = state;
            this.UiData = ui_data;
        }
        // Parameterless constructor for Unity editor and serialization
        public ClassifyData() { }
    }


}
