// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Activities;
using EduObject.Activities.MediaContentTypes;

namespace EduObject.Activities.MatchPairs
{
    [Serializable]
    public class IntegerPair{
        [JsonProperty("left_index")]
        public int LeftIndex { get; set; }
        [JsonProperty("right_index")]
        public int RightIndex { get; set; }
        public IntegerPair(int left_index, int right_index)    {
            this.LeftIndex = left_index;
            this.RightIndex = right_index;
        }
        // Parameterless constructor for Unity editor and serialization
        public IntegerPair() { }
    }

    [Serializable]
    public class MatchPairsUIItem{
        [JsonProperty("index")]
        public int Index { get; set; }
        [JsonProperty("content")]
        public MediaContentType Content { get; set; }
        public MatchPairsUIItem(int index, MediaContentType content)    {
            this.Index = index;
            this.Content = content;
        }
        // Parameterless constructor for Unity editor and serialization
        public MatchPairsUIItem() { }
    }

    [Serializable]
    public class MatchPairsUIRow{
        [JsonProperty("left")]
        public MatchPairsUIItem Left { get; set; }
        [JsonProperty("right")]
        public MatchPairsUIItem Right { get; set; }
        public MatchPairsUIRow(MatchPairsUIItem left, MatchPairsUIItem right)    {
            this.Left = left;
            this.Right = right;
        }
        // Parameterless constructor for Unity editor and serialization
        public MatchPairsUIRow() { }
    }

    [Serializable]
    public class MatchPairsUIData{
        [JsonProperty("common")]
        public UIDataCommonFields Common { get; set; } = null;
        [JsonProperty("rows")]
        public List<MatchPairsUIRow> Rows { get; set; } = new List<MatchPairsUIRow>();
        [JsonProperty("action")]
        public UIAction Action { get; set; } = null;
        public MatchPairsUIData(UIDataCommonFields common, List<MatchPairsUIRow> rows, UIAction action)    {
            this.Common = common;
            this.Rows = rows;
            this.Action = action;
        }
        // Parameterless constructor for Unity editor and serialization
        public MatchPairsUIData() { }
    }


}
