// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Activities.Guess;

namespace EduObject.Chemistry.PeriodicTable.Activities.Guess
{
    [JsonConverter(typeof(PeriodicTableTypeJsonConverter))]
    public enum PeriodicTableType
    {
        FULL,
        FIRST3ROWS
    }

    public class PeriodicTableTypeJsonConverter : JsonConverter<PeriodicTableType>
    {
        private static readonly Dictionary<string, PeriodicTableType> StringToEnum = new Dictionary<string, PeriodicTableType>
        {
            { "Full", PeriodicTableType.FULL },        { "First3Rows", PeriodicTableType.FIRST3ROWS }    };

        private static readonly Dictionary<PeriodicTableType, string> EnumToString = new Dictionary<PeriodicTableType, string>
        {
            { PeriodicTableType.FULL, "Full" },        { PeriodicTableType.FIRST3ROWS, "First3Rows" }    };

        public override void WriteJson(JsonWriter writer, PeriodicTableType value, JsonSerializer serializer)
        {
            writer.WriteValue(EnumToString[value]);
        }

        public override PeriodicTableType ReadJson(JsonReader reader, Type objectType, PeriodicTableType existingValue, bool hasExistingValue, JsonSerializer serializer)
        {
            string stringValue = (string)reader.Value;
            return StringToEnum[stringValue];
        }
    }

    [Serializable]
    public class PeriodicTableGuessUIData : GuessUIData{
        [JsonProperty("filter_mode")]
        public PeriodicTableType FilterMode { get; set; } = PeriodicTableType.FULL;
        [JsonProperty("element_states")]
        public string ElementStates { get; set; } = "";
        public PeriodicTableGuessUIData(PeriodicTableType filter_mode, string element_states): base()
        {
            this.FilterMode = filter_mode;
            this.ElementStates = element_states;
        }
        // Parameterless constructor for Unity editor and serialization
        public PeriodicTableGuessUIData() { }
    }


}
