// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using JsonSubTypes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(DHMError), "DHMError")]
[JsonSubtypes.KnownSubType(typeof(DHMChatInfo), "DHMChatInfo")]
[JsonSubtypes.KnownSubType(typeof(DHMSetChatView), "DHMSetChatView")]
[JsonSubtypes.KnownSubType(typeof(DHMAgentChatView), "DHMAgentChatView")]
[JsonSubtypes.KnownSubType(typeof(DHMAddHuman), "DHMAddHuman")]
[JsonSubtypes.KnownSubType(typeof(DHMAddAgent), "DHMAddAgent")]
[JsonSubtypes.KnownSubType(typeof(DHMHumanTextChunk), "DHMHumanTextChunk")]
[JsonSubtypes.KnownSubType(typeof(DHMHumanAction), "DHMHumanAction")]
[JsonSubtypes.KnownSubType(typeof(DHMHumanAudioChunk), "DHMHumanAudioChunk")]
[JsonSubtypes.KnownSubType(typeof(DHMHumanImage), "DHMHumanImage")]
[JsonSubtypes.KnownSubType(typeof(DHMAgentTextChunk), "DHMAgentTextChunk")]
[JsonSubtypes.KnownSubType(typeof(DHMAgentTimedMediaChunk), "DHMAgentTimedMediaChunk")]
[JsonSubtypes.KnownSubType(typeof(DHMAgentActionDefinition), "DHMAgentActionDefinition")]
[JsonSubtypes.KnownSubType(typeof(DHMMetadata), "DHMMetadata")]
public class DHMessage{
    public string type;
    public List<IntOrString> id;
    public DHMessage(string type, List<IntOrString> id)    {
        this.type = type;
        this.id = id;
    }
}
[Serializable]
public class DHMError : DHMessage
{
    public int code;
    public string codeDescription;
    public int service;
    public string serviceDescription;
    public int serviceProvider;
    public string serviceProviderDescription;
    public string message;
    public DHMError(string type, List<IntOrString> id, int code, string codeDescription, int service, string serviceDescription, int serviceProvider, string serviceProviderDescription, string message): base(type, id)
    {
        this.code = code;
        this.codeDescription = codeDescription;
        this.service = service;
        this.serviceDescription = serviceDescription;
        this.serviceProvider = serviceProvider;
        this.serviceProviderDescription = serviceProviderDescription;
        this.message = message;
    }
}
[Serializable]
public class DHMChatInfo : DHMessage
{
    public DHMChatInfo(string type, List<IntOrString> id): base(type, id)
    {
    }
}
[Serializable]
public class DHMSetChatView : DHMessage
{
    public ChatViewConfig view;
    public DHMSetChatView(string type, List<IntOrString> id, ChatViewConfig view): base(type, id)
    {
        this.view = view;
    }
}
[Serializable]
public class DHMAgentChatView : DHMessage
{
    public int agentId;
    public ChatViewInfo view;
    public DHMAgentChatView(string type, List<IntOrString> id, int agentId, ChatViewInfo view): base(type, id)
    {
        this.agentId = agentId;
        this.view = view;
    }
}
[Serializable]
public class DHMAddHuman : DHMessage
{
    public int humanId;
    public DHMAddHuman(string type, List<IntOrString> id, int humanId): base(type, id)
    {
        this.humanId = humanId;
    }
}
[Serializable]
public class DHMAddAgent : DHMessage
{
    public int agentId;
    public DHMAddAgent(string type, List<IntOrString> id, int agentId): base(type, id)
    {
        this.agentId = agentId;
    }
}
[Serializable]
public class DHMHumanTextChunk : DHMessage
{
    public int humanId;
    public string text;
    public bool final;
    public DHMHumanTextChunk(string type, List<IntOrString> id, int humanId, string text, bool final): base(type, id)
    {
        this.humanId = humanId;
        this.text = text;
        this.final = final;
    }
}
[Serializable]
public class DHMHumanAction : DHMessage
{
    public int humanId;
    public string actionType;
    public string action;
    public DHMHumanAction(string type, List<IntOrString> id, int humanId, string actionType, string action): base(type, id)
    {
        this.humanId = humanId;
        this.actionType = actionType;
        this.action = action;
    }
}
[Serializable]
public class DHMHumanAudioChunk : DHMessage
{
    public int humanId;
    public string buffer;
    public int sampleIndex;
    public int sampleRate;
    public int channels;
    public string format;
    public bool final;
    public string language;
    public DHMHumanAudioChunk(string type, List<IntOrString> id, int humanId, string buffer, int sampleIndex, int sampleRate, int channels, string format, bool final, string language): base(type, id)
    {
        this.humanId = humanId;
        this.buffer = buffer;
        this.sampleIndex = sampleIndex;
        this.sampleRate = sampleRate;
        this.channels = channels;
        this.format = format;
        this.final = final;
        this.language = language;
    }
}
[Serializable]
public class DHMHumanImage : DHMessage
{
    public int humanId;
    public string text;
    public string url;
    public DHMHumanImage(string type, List<IntOrString> id, int humanId, string text, string url): base(type, id)
    {
        this.humanId = humanId;
        this.text = text;
        this.url = url;
    }
}
[Serializable]
public class DHMAgentTextChunk : DHMessage
{
    public int agentId;
    public string text;
    public bool final;
    public bool system;
    public DHMAgentTextChunk(string type, List<IntOrString> id, int agentId, string text, bool final, bool system): base(type, id)
    {
        this.agentId = agentId;
        this.text = text;
        this.final = final;
        this.system = system;
    }
}
[Serializable]
public class DHMAgentTimedMediaChunk : DHMessage
{
    public int agentId;
    public List<TimedMedia>? timedMedia;
    public DHMAgentTimedMediaChunk(string type, List<IntOrString> id, int agentId, List<TimedMedia>? timedMedia): base(type, id)
    {
        this.agentId = agentId;
        this.timedMedia = timedMedia;
    }
}
[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(TimedAudio), "TimedAudio")]
[JsonSubtypes.KnownSubType(typeof(TimedViseme), "TimedViseme")]
[JsonSubtypes.KnownSubType(typeof(TimedText), "TimedText")]
[JsonSubtypes.KnownSubType(typeof(TimedAction), "TimedAction")]
[JsonSubtypes.KnownSubType(typeof(TimedMetadata), "TimedMetadata")]
public class TimedMedia{
    public string type;
    public float time;
    public float? duration;
    public TimedMedia(string type, float time, float? duration)    {
        this.type = type;
        this.time = time;
        this.duration = duration;
    }
}
[Serializable]
public class TimedAudio : TimedMedia
{
    public string buffer;
    public int sampleIndex;
    public int sampleRate;
    public int channels;
    public int audioByteSize;
    public TimedAudio(string type, float time, float? duration, string buffer, int sampleIndex, int sampleRate, int channels, int audioByteSize): base(type, time, duration)
    {
        this.buffer = buffer;
        this.sampleIndex = sampleIndex;
        this.sampleRate = sampleRate;
        this.channels = channels;
        this.audioByteSize = audioByteSize;
    }
}
[Serializable]
public class TimedViseme : TimedMedia
{
    public string viseme;
    public TimedViseme(string type, float time, float? duration, string viseme): base(type, time, duration)
    {
        this.viseme = viseme;
    }
}
[Serializable]
public class TimedText : TimedMedia
{
    public string textType;
    public string text;
    public TimedText(string type, float time, float? duration, string textType, string text): base(type, time, duration)
    {
        this.textType = textType;
        this.text = text;
    }
}
[Serializable]
public class ActionDefinition{
    public string type;
    public List<List<string>> attributes;
    public ActionDefinition(string type, List<List<string>> attributes)    {
        this.type = type;
        this.attributes = attributes;
    }
}
[Serializable]
public class TimedAction : TimedMedia
{
    public string span;
    public int startId;
    public int endId;
    public string? actionId;
    public ActionDefinition? actionDefinition;
    public TimedAction(string type, float time, float? duration, string span, int startId, int endId, string? actionId, ActionDefinition? actionDefinition): base(type, time, duration)
    {
        this.span = span;
        this.startId = startId;
        this.endId = endId;
        this.actionId = actionId;
        this.actionDefinition = actionDefinition;
    }
}
[Serializable]
public class TimedMetadata : TimedMedia
{
    public int? totalAudioSamples;
    public int sampleRate;
    public int channels;
    public int totalAudioByteSize;
    public bool final;
    public TimedMetadata(string type, float time, float? duration, int? totalAudioSamples, int sampleRate, int channels, int totalAudioByteSize, bool final): base(type, time, duration)
    {
        this.totalAudioSamples = totalAudioSamples;
        this.sampleRate = sampleRate;
        this.channels = channels;
        this.totalAudioByteSize = totalAudioByteSize;
        this.final = final;
    }
}
[Serializable]
public class DHMAgentActionDefinition : DHMessage
{
    public int agentId;
    public string actionId;
    public ActionDefinition actionDefinition;
    public DHMAgentActionDefinition(string type, List<IntOrString> id, int agentId, string actionId, ActionDefinition actionDefinition): base(type, id)
    {
        this.agentId = agentId;
        this.actionId = actionId;
        this.actionDefinition = actionDefinition;
    }
}
[Serializable]
public class DHMMetadata : DHMessage
{
    public List<List<string>>? metadata;
    public DHMMetadata(string type, List<IntOrString> id, List<List<string>>? metadata): base(type, id)
    {
        this.metadata = metadata;
    }
}
[Serializable]
public class ChatViewTextConfig{
    public bool enabled = true;
    public bool source = false;
    public ChatViewTextConfig(bool enabled, bool source)    {
        this.enabled = enabled;
        this.source = source;
    }
}
[Serializable]
public class ChatViewSpeechConfig{
    public bool enabled = false;
    public ChatViewSpeechConfig(bool enabled)    {
        this.enabled = enabled;
    }
}
[Serializable]
public class ChatViewVisemeConfig{
    public bool enabled = false;
    public ChatViewVisemeConfig(bool enabled)    {
        this.enabled = enabled;
    }
}
[Serializable]
public class ChatViewConfig{
    public string language = "en-US";
    public ChatViewTextConfig text;
    public ChatViewSpeechConfig speech;
    public ChatViewVisemeConfig viseme;
    public ChatViewConfig(string language, ChatViewTextConfig text, ChatViewSpeechConfig speech, ChatViewVisemeConfig viseme)    {
        this.language = language;
        this.text = text;
        this.speech = speech;
        this.viseme = viseme;
    }
}
[Serializable]
public class ChatViewTextInfo{
    public bool enabled = true;
    public bool source = false;
    public ChatViewTextInfo(bool enabled, bool source)    {
        this.enabled = enabled;
        this.source = source;
    }
}
[Serializable]
public class ChatViewSpeechInfo{
    public bool enabled = false;
    public float sampleRate = -1;
    public float channels = 1;
    public float bitsPerSample = 16;
    public string format = "PCM";
    public ChatViewSpeechInfo(bool enabled, float sampleRate, float channels, float bitsPerSample, string format)    {
        this.enabled = enabled;
        this.sampleRate = sampleRate;
        this.channels = channels;
        this.bitsPerSample = bitsPerSample;
        this.format = format;
    }
}
[Serializable]
public class ChatViewVisemeInfo{
    public bool enabled = false;
    public ChatViewVisemeInfo(bool enabled)    {
        this.enabled = enabled;
    }
}
[Serializable]
public class ChatViewInfo{
    public string language = "en-US";
    public ChatViewTextInfo text;
    public ChatViewSpeechInfo speech;
    public ChatViewVisemeInfo viseme;
    public ChatViewInfo(string language, ChatViewTextInfo text, ChatViewSpeechInfo speech, ChatViewVisemeInfo viseme)    {
        this.language = language;
        this.text = text;
        this.speech = speech;
        this.viseme = viseme;
    }
}
