// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using JsonSubTypes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
[Serializable]
public class style{
    public FloatOrString? width;
    public FloatOrString? height;
    public ObjectOrString? margin;
    public ObjectOrString? padding;
    public string? backgroundColor;
    public string? color;
    public FloatOrString? fontSize;
    public FloatOrString? fontWeight;
    public string? fontFamily;
    public string? textAlign;
    public string? border;
    public FloatOrString? borderRadius;
    public string? boxShadow;
    public string? display;
    public string? position;
    public FloatOrString? top;
    public FloatOrString? left;
    public FloatOrString? right;
    public FloatOrString? bottom;
    public float? zIndex;
    public float? opacity;
    public string? overflow;
    public string? cursor;
    public bool visible = true;
    public style(FloatOrString? width, FloatOrString? height, ObjectOrString? margin, ObjectOrString? padding, string? backgroundColor, string? color, FloatOrString? fontSize, FloatOrString? fontWeight, string? fontFamily, string? textAlign, string? border, FloatOrString? borderRadius, string? boxShadow, string? display, string? position, FloatOrString? top, FloatOrString? left, FloatOrString? right, FloatOrString? bottom, float? zIndex, float? opacity, string? overflow, string? cursor, bool visible)    {
        this.width = width;
        this.height = height;
        this.margin = margin;
        this.padding = padding;
        this.backgroundColor = backgroundColor;
        this.color = color;
        this.fontSize = fontSize;
        this.fontWeight = fontWeight;
        this.fontFamily = fontFamily;
        this.textAlign = textAlign;
        this.border = border;
        this.borderRadius = borderRadius;
        this.boxShadow = boxShadow;
        this.display = display;
        this.position = position;
        this.top = top;
        this.left = left;
        this.right = right;
        this.bottom = bottom;
        this.zIndex = zIndex;
        this.opacity = opacity;
        this.overflow = overflow;
        this.cursor = cursor;
        this.visible = visible;
    }
}
[Serializable]
[JsonConverter(typeof(JsonSubtypes), "type")]
[JsonSubtypes.KnownSubType(typeof(textObject), "text")]
[JsonSubtypes.KnownSubType(typeof(buttonObject), "button")]
[JsonSubtypes.KnownSubType(typeof(inputObject), "input")]
[JsonSubtypes.KnownSubType(typeof(imageObject), "image")]
[JsonSubtypes.KnownSubType(typeof(containerObject), "container")]
[JsonSubtypes.KnownSubType(typeof(listObject), "list")]
[JsonSubtypes.KnownSubType(typeof(modalObject), "modal")]
[JsonSubtypes.KnownSubType(typeof(formObject), "form")]
[JsonSubtypes.KnownSubType(typeof(tableObject), "table")]
public class baseUIObject{
    public string type;
    public string? id = null;
    public NullOrStyle style = null;
    public bool enabled = true;
    public string? className = null;
    public object? metadata = null;
    public baseUIObject(string type, string? id, NullOrStyle style, bool enabled, string? className, object? metadata)    {
        this.type = type;
        this.id = id;
        this.style = style;
        this.enabled = enabled;
        this.className = className;
        this.metadata = metadata;
    }
}
[Serializable]
public class textObject : baseUIObject
{
    public new string type = "text";
    public string content;
    public string? placeholder;
    public textObject(string? id, NullOrStyle style, bool enabled, string? className, object? metadata, string type, string content, string? placeholder): base("text", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.content = content;
        this.placeholder = placeholder;
    }
}
[Serializable]
public class buttonObject : baseUIObject
{
    public new string type = "button";
    public string label;
    public string? action;
    public string? variant;
    public bool disabled = false;
    public buttonObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, string label, string? action, string? variant, bool disabled): base("button", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.label = label;
        this.action = action;
        this.variant = variant;
        this.disabled = disabled;
    }
}
[Serializable]
public class inputObject : baseUIObject
{
    public new string type = "input";
    public string inputType = "text";
    public string? value;
    public string? placeholder;
    public bool required = false;
    public int? maxLength;
    public int? minLength;
    public inputObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, string inputType, string? value, string? placeholder, bool required, int? maxLength, int? minLength): base("input", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.inputType = inputType;
        this.value = value;
        this.placeholder = placeholder;
        this.required = required;
        this.maxLength = maxLength;
        this.minLength = minLength;
    }
}
[Serializable]
public class imageObject : baseUIObject
{
    public new string type = "image";
    public string src;
    public string alt;
    public string? caption;
    public imageObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, string src, string alt, string? caption): base("image", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.src = src;
        this.alt = alt;
        this.caption = caption;
    }
}
[Serializable]
public class containerObject : baseUIObject
{
    public new string type = "container";
    public string layout = "block";
    public string direction = "column";
    public string? justifyContent;
    public string? alignItems;
    public List<uiObjectUnion>? children;
    public containerObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, string layout, string direction, string? justifyContent, string? alignItems, List<uiObjectUnion>? children): base("container", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.layout = layout;
        this.direction = direction;
        this.justifyContent = justifyContent;
        this.alignItems = alignItems;
        this.children = children;
    }
}
[Serializable]
public class listObject : baseUIObject
{
    public new string type = "list";
    public bool ordered = false;
    public List<uiObjectUnion>? items;
    public listObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, bool ordered, List<uiObjectUnion>? items): base("list", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.ordered = ordered;
        this.items = items;
    }
}
[Serializable]
public class modalObject : baseUIObject
{
    public new string type = "modal";
    public string title;
    public uiObjectUnion content;
    public bool closable = true;
    public bool backdrop = true;
    public modalObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, string title, uiObjectUnion content, bool closable, bool backdrop): base("modal", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.title = title;
        this.content = content;
        this.closable = closable;
        this.backdrop = backdrop;
    }
}
[Serializable]
public class formObject : baseUIObject
{
    public new string type = "form";
    public string? action;
    public string method = "POST";
    public List<uiObjectUnion> fields;
    public formObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, string? action, string method, List<uiObjectUnion> fields): base("form", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.action = action;
        this.method = method;
        this.fields = fields;
    }
}
[Serializable]
public class tableObject : baseUIObject
{
    public new string type = "table";
    public List<string> headers;
    public List<List<uiObjectUnion>> rows;
    public bool sortable = false;
    public tableObject(string id, NullOrStyle style, bool enabled, string className, object metadata, string type, List<string> headers, List<List<uiObjectUnion>> rows, bool sortable): base("table", id, style, enabled, className, metadata)
    {
        this.type = type;
        this.headers = headers;
        this.rows = rows;
        this.sortable = sortable;
    }
}
