// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Activities;
using EduObject.Activities.MediaContentTypes;

namespace EduObject.Activities.Quiz
{
    [Serializable]
    public class QuizAnswer{
        [JsonProperty("content")]
        public MediaContentType Content { get; set; }
        [JsonProperty("is_correct")]
        public bool IsCorrect { get; set; }
        public QuizAnswer(MediaContentType content, bool is_correct)    {
            this.Content = content;
            this.IsCorrect = is_correct;
        }
        // Parameterless constructor for Unity editor and serialization
        public QuizAnswer() { }
    }

    [Serializable]
    public class QuizUIAnswerOption{
        [JsonProperty("answer")]
        public QuizAnswer Answer { get; set; }
        [JsonProperty("is_selected")]
        public bool IsSelected { get; set; } = false;
        [JsonProperty("action")]
        public UIAction Action { get; set; } = null;
        public QuizUIAnswerOption(QuizAnswer answer, bool is_selected, UIAction action)    {
            this.Answer = answer;
            this.IsSelected = is_selected;
            this.Action = action;
        }
        // Parameterless constructor for Unity editor and serialization
        public QuizUIAnswerOption() { }
    }

    [Serializable]
    public class QuizUIData{
        [JsonProperty("common")]
        public UIDataCommonFields Common { get; set; } = null;
        [JsonProperty("answers")]
        public List<QuizUIAnswerOption> Answers { get; set; } = new List<QuizUIAnswerOption>();
        public QuizUIData(UIDataCommonFields common, List<QuizUIAnswerOption> answers)    {
            this.Common = common;
            this.Answers = answers;
        }
        // Parameterless constructor for Unity editor and serialization
        public QuizUIData() { }
    }


}
