// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using EduObject.Maths.BasicOperations.Activities.Complete;

namespace EduObject.Maths.BasicOperations.Multiplication.Activities.Complete
{
    [Serializable]
    public class MultiplicationCompleteUIData{
        [JsonProperty("question_text")]
        public string QuestionText { get; set; } = "";
        [JsonProperty("multiplicand_row")]
        public OperandRowState MultiplicandRow { get; set; } = null;
        [JsonProperty("multiplier_row")]
        public OperandRowState MultiplierRow { get; set; } = null;
        [JsonProperty("partial_product_carry_rows")]
        public List<InputRowState> PartialProductCarryRows { get; set; } = new List<InputRowState>();
        [JsonProperty("partial_product_rows")]
        public List<InputRowState> PartialProductRows { get; set; } = new List<InputRowState>();
        [JsonProperty("final_carry_row")]
        public InputRowState FinalCarryRow { get; set; } = null;
        [JsonProperty("final_sum_row")]
        public InputRowState FinalSumRow { get; set; } = null;
        public MultiplicationCompleteUIData(string question_text, OperandRowState multiplicand_row, OperandRowState multiplier_row, List<InputRowState> partial_product_carry_rows, List<InputRowState> partial_product_rows, InputRowState final_carry_row, InputRowState final_sum_row)    {
            this.QuestionText = question_text;
            this.MultiplicandRow = multiplicand_row;
            this.MultiplierRow = multiplier_row;
            this.PartialProductCarryRows = partial_product_carry_rows;
            this.PartialProductRows = partial_product_rows;
            this.FinalCarryRow = final_carry_row;
            this.FinalSumRow = final_sum_row;
        }
        // Parameterless constructor for Unity editor and serialization
        public MultiplicationCompleteUIData() { }
    }


}
