// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using JsonSubTypes;
using Newtonsoft.Json;
using System;

namespace EduObject.Activities.MediaContentTypes
{
    [Serializable]
    public class MediaContentText : MediaContentType{
        [JsonProperty("type")]
        public const string type = "text";
        [JsonProperty("text")]
        public string Text { get; set; }
        public MediaContentText(string text): base()
        {
            this.Text = text;
        }
        // Parameterless constructor for Unity editor and serialization
        public MediaContentText() { }
    }

    [Serializable]
    public class MediaContentImage : MediaContentType{
        [JsonProperty("type")]
        public const string type = "image";
        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }
        public MediaContentImage(string image_url): base()
        {
            this.ImageUrl = image_url;
        }
        // Parameterless constructor for Unity editor and serialization
        public MediaContentImage() { }
    }

    [Serializable]
    public class MediaContentTextAndImage : MediaContentType{
        [JsonProperty("type")]
        public const string type = "text_and_image";
        [JsonProperty("text")]
        public string Text { get; set; }
        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }
        public MediaContentTextAndImage(string text, string image_url): base()
        {
            this.Text = text;
            this.ImageUrl = image_url;
        }
        // Parameterless constructor for Unity editor and serialization
        public MediaContentTextAndImage() { }
    }

    [Serializable]
    [JsonConverter(typeof(JsonSubtypes), "type")]
    [JsonSubtypes.KnownSubType(typeof(MediaContentText), "text")]
    [JsonSubtypes.KnownSubType(typeof(MediaContentImage), "image")]
    [JsonSubtypes.KnownSubType(typeof(MediaContentTextAndImage), "text_and_image")]
    public class MediaContentType{
        public MediaContentType()    {
        }
    }


}
