// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using System;
using System.Collections.Generic;
using EduObject.Activities;
using Newtonsoft.Json;

namespace EduObject.Activities
{
    [Serializable]
    public class UIStateChangeOperation
    {
        [JsonProperty("type")]
        public const string type = "state_change";

        [JsonProperty("path")]
        public string Path { get; set; }

        [JsonProperty("op")]
        public string Op { get; set; }

        [JsonProperty("value_type")]
        public List<string> ValueType { get; set; }

        [JsonProperty("value")]
        public object? Value { get; set; }

        public UIStateChangeOperation(
            string path,
            string op,
            List<string> value_type,
            object? value
        )
        {
            this.Path = path;
            this.Op = op;
            this.ValueType = value_type;
            this.Value = value;
        }

        // Parameterless constructor for Unity editor and serialization
        public UIStateChangeOperation() { }
    }

    [Serializable]
    public class UIAction
    {
        [JsonProperty("operations")]
        public List<UIStateChangeOperation> Operations { get; set; }

        public UIAction(List<UIStateChangeOperation> operations)
        {
            this.Operations = operations;
        }

        // Parameterless constructor for Unity editor and serialization
        public UIAction() { }
    }

    [Serializable]
    public class UIDataCommonFields
    {
        [JsonProperty("question")]
        public string Question { get; set; }

        [JsonProperty("answer")]
        public string Answer { get; set; }

        public UIDataCommonFields(string question, string answer)
        {
            this.Question = question;
            this.Answer = answer;
        }

        // Parameterless constructor for Unity editor and serialization
        public UIDataCommonFields() { }
    }
}
