// Generated by json_schema_to_code v1.0.1 : json_schema_to_code
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace EduObject.Chemistry.PeriodicTable
{
    [Serializable]
    public class PeriodicTableData{
        [JsonProperty("type")]
        public const string type = "chemistry/periodic_table";
        [JsonProperty("periodic_table")]
        public PeriodicTableDataPeriodicTable PeriodicTable { get; set; }
        public PeriodicTableData(PeriodicTableDataPeriodicTable periodic_table)    {
            this.PeriodicTable = periodic_table;
        }
        // Parameterless constructor for Unity editor and serialization
        public PeriodicTableData() { }
    }

    [Serializable]
    public class Elements{
        [JsonProperty("atomic_number")]
        public int AtomicNumber { get; set; }
        [JsonProperty("symbol")]
        public string Symbol { get; set; }
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("atomic_mass")]
        public float AtomicMass { get; set; }
        [JsonProperty("group")]
        public int Group { get; set; }
        [JsonProperty("period")]
        public int Period { get; set; }
        [JsonProperty("block")]
        public string Block { get; set; }
        [JsonProperty("category")]
        public string Category { get; set; }
        [JsonProperty("electron_configuration")]
        public string ElectronConfiguration { get; set; }
        [JsonProperty("electronegativity")]
        public float Electronegativity { get; set; }
        [JsonProperty("oxidation_states")]
        public List<int> OxidationStates { get; set; }
        [JsonProperty("melting_point")]
        public float MeltingPoint { get; set; }
        [JsonProperty("boiling_point")]
        public float BoilingPoint { get; set; }
        [JsonProperty("density")]
        public float Density { get; set; }
        [JsonProperty("phase_at_stp")]
        public string PhaseAtStp { get; set; }
        [JsonProperty("discovered_by")]
        public string DiscoveredBy { get; set; }
        [JsonProperty("discovery_year")]
        public int DiscoveryYear { get; set; }
        [JsonProperty("radioactive")]
        public bool Radioactive { get; set; }
        public Elements(int atomic_number, string symbol, string name, float atomic_mass, int group, int period, string block, string category, string electron_configuration, float electronegativity, List<int> oxidation_states, float melting_point, float boiling_point, float density, string phase_at_stp, string discovered_by, int discovery_year, bool radioactive)    {
            this.AtomicNumber = atomic_number;
            this.Symbol = symbol;
            this.Name = name;
            this.AtomicMass = atomic_mass;
            this.Group = group;
            this.Period = period;
            this.Block = block;
            this.Category = category;
            this.ElectronConfiguration = electron_configuration;
            this.Electronegativity = electronegativity;
            this.OxidationStates = oxidation_states;
            this.MeltingPoint = melting_point;
            this.BoilingPoint = boiling_point;
            this.Density = density;
            this.PhaseAtStp = phase_at_stp;
            this.DiscoveredBy = discovered_by;
            this.DiscoveryYear = discovery_year;
            this.Radioactive = radioactive;
        }
        // Parameterless constructor for Unity editor and serialization
        public Elements() { }
    }

    [Serializable]
    public class PeriodicTableDataPeriodicTable{
        [JsonProperty("elements")]
        public List<Elements> Elements { get; set; }
        public PeriodicTableDataPeriodicTable(List<Elements> elements)    {
            this.Elements = elements;
        }
        // Parameterless constructor for Unity editor and serialization
        public PeriodicTableDataPeriodicTable() { }
    }


}
